// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sisgef;

namespace Sisgef.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200619034640_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sisgef.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Contato")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Contato2")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Rua")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoDeServico")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("Sisgef.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnoFabricacao")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Chassi")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Combustivel")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cor")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DocumentoDoProprietario")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LocalDeEmplacamento")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NomeDoProprietario")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Odometro")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Renavam")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoCarroceria")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoDoVeiculo")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
